import {useEffect,useState} from 'react';
import {api,date,money} from '../api.js';
import {Empty,ErrorBox,Loader} from '../components.jsx';
import {Bell,Building2,Flag,Shield,Users,Activity,Settings} from 'lucide-react';

export default function AdminPage(){
 const [data,setData]=useState(null),[tab,setTab]=useState('reports'),[error,setError]=useState('');
 const load=()=>{setError('');return Promise.all([api('/admin/dashboard'),api('/admin/reports'),api('/admin/users'),api('/admin/listings'),api('/admin/activity'),api('/admin/settings')]).then(([stats,reports,users,listings,activity,settings])=>setData({stats,reports,users,listings,activity,settings})).catch(e=>setError(e.message));};
 useEffect(()=>{load();},[]);
 async function patch(path,body){try{await api(path,{method:'PATCH',body:JSON.stringify(body)});await load();}catch(e){setError(e.message);}}
 async function saveSettings(e){e.preventDefault();const f=new FormData(e.currentTarget),body={maintenance_mode:f.has('maintenance_mode'),allow_registration:f.has('allow_registration'),require_listing_approval:f.has('require_listing_approval'),community_notice:f.get('community_notice')};try{await api('/admin/settings',{method:'PUT',body:JSON.stringify(body)});await load();}catch(x){setError(x.message);}}
 if(!data&&!error)return <Loader/>; if(!data)return <div className="page"><ErrorBox message={error}/><button className="secondary" onClick={load}>Try again</button></div>;
 const {stats,reports,users,listings,activity,settings}=data;
 return <div className="page"><section className="page-title"><div><span className="eyebrow">Administrator access</span><h1>Platform control centre</h1><p>Moderation, account controls and platform operations unavailable to regular users.</p></div></section><ErrorBox message={error}/><div className="stats-grid"><article><Users/><span>Members</span><b>{stats.users.total}</b><small>{stats.users.new} new this month</small></article><article><Building2/><span>Listings</span><b>{stats.listings.total}</b><small>{stats.listings.available} available</small></article><article><Flag/><span>Open reports</span><b>{stats.reports.open}</b><small>{stats.reports.total} all time</small></article><article><Shield/><span>Visible posts</span><b>{stats.posts.total}</b><small>Community activity</small></article></div><div className="admin-tabs">{[['reports',Flag,'Reports'],['users',Users,'Users'],['listings',Building2,'Listings'],['activity',Activity,'Audit log'],['settings',Settings,'Settings']].map(([id,Icon,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={15}/>{label}</button>)}</div>
 {tab==='reports'&&(reports.length?<Table headers={['Report','Target','Status','Submitted','Action']}>{reports.map(r=><Row key={r.id}><span><b>{r.reason}</b><small>by {r.reporter_name}</small></span><span>{r.target_type}</span><span className={`status ${r.status}`}>{r.status}</span><span>{date(r.created_at)}</span><span>{['open','reviewing'].includes(r.status)&&<><button onClick={()=>patch('/admin/reports/'+r.id,{status:'resolved',resolution_note:'Resolved by administrator'})}>Resolve</button><button onClick={()=>patch('/admin/reports/'+r.id,{status:'dismissed',resolution_note:'Dismissed by administrator'})}>Dismiss</button></>}</span></Row>)}</Table>:<Empty title="No reports" body="The moderation queue is clear."/>)}
 {tab==='users'&&<Table headers={['Member','Role','Status','Joined','Admin controls']}>{users.map(u=><Row key={u.id}><span><b>{u.first_name} {u.last_name}</b><small>{u.email}</small></span><select value={u.role} onChange={e=>patch('/admin/users/'+u.id,{role:e.target.value})}><option value="user">user</option><option value="admin">admin</option></select><span className={`status ${u.status}`}>{u.status}</span><span>{date(u.created_at)}</span><select value={u.status} onChange={e=>patch('/admin/users/'+u.id,{status:e.target.value})}><option>active</option><option>suspended</option><option>banned</option></select></Row>)}</Table>}
 {tab==='listings'&&<Table headers={['Listing','Owner','Rent','Visibility','Status']}>{listings.map(l=><Row key={l.id}><span><b>{l.title}</b><small>{l.city}, {l.province}</small></span><span>{l.owner_name}</span><span>{money(l.monthly_rent)}</span><select value={String(l.is_approved)} onChange={e=>patch('/admin/listings/'+l.id,{is_approved:e.target.value==='true'})}><option value="true">Approved</option><option value="false">Hidden</option></select><select value={l.status} onChange={e=>patch('/admin/listings/'+l.id,{status:e.target.value})}>{['available','pending','occupied','unavailable','removed'].map(x=><option key={x}>{x}</option>)}</select></Row>)}</Table>}
 {tab==='activity'&&(activity.length?<Table headers={['Action','Administrator','Target','Details','When']}>{activity.map(a=><Row key={a.id}><b>{a.action.replaceAll('_',' ')}</b><span>{a.admin_name||'System'}</span><span>{a.target_type||'Platform'}</span><small>{JSON.stringify(a.details)}</small><span>{date(a.created_at)}</span></Row>)}</Table>:<Empty title="No admin activity" body="Administrative changes will be recorded here."/>)}
 {tab==='settings'&&<form className="form-card admin-settings" onSubmit={saveSettings}><h2>Platform settings</h2><label className="check"><input type="checkbox" name="allow_registration" defaultChecked={settings.allow_registration??true}/>Allow new registrations</label><label className="check"><input type="checkbox" name="require_listing_approval" defaultChecked={settings.require_listing_approval??false}/>Require listing approval</label><label className="check"><input type="checkbox" name="maintenance_mode" defaultChecked={settings.maintenance_mode??false}/>Maintenance mode</label><label>Community notice<textarea name="community_notice" rows="4" defaultValue={settings.community_notice||''}/></label><button className="primary">Save platform settings</button></form>}
 </div>;
}
function Table({headers,children}){return <div className="data-table"><div className="data-row head">{headers.map(x=><span key={x}>{x}</span>)}</div>{children}</div>}
function Row({children}){return <div className="data-row">{children}</div>}

export function NotificationsPage(){const[items,setItems]=useState(null),[error,setError]=useState('');const load=()=>api('/notifications').then(setItems).catch(e=>setError(e.message));useEffect(()=>{load();},[]);async function read(id){await api(`/notifications/${id}/read`,{method:'PATCH'});setItems(items.map(x=>x.id===id?{...x,read_at:new Date().toISOString()}:x));}return <div className="page narrow"><section className="page-title"><div><span className="eyebrow">Updates</span><h1>Notifications</h1></div></section><ErrorBox message={error}/>{!items&&!error?<Loader/>:items?.length?<div className="notification-list">{items.map(n=><button key={n.id} className={n.read_at?'read':'unread'} onClick={()=>read(n.id)}><span className="notification-icon"><Bell/></span><span><b>{n.title}</b><p>{n.body}</p><small>{date(n.created_at)}</small></span>{!n.read_at&&<i/>}</button>)}</div>:!error&&<Empty title="All caught up" body="New messages and important updates will appear here."/>}</div>}
