import {useState} from 'react';
import {api} from '../api.js';
import {Logo,ErrorBox} from '../components.jsx';
import {CheckCircle2,MapPin,Users,ShieldCheck} from 'lucide-react';

const provinces=['Gauteng','Western Cape','KwaZulu-Natal','Eastern Cape','Free State','Limpopo','Mpumalanga','North West','Northern Cape'];
export default function AuthPage({onAuthenticated}){
  const [mode,setMode]=useState('login'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function submit(e){e.preventDefault();setBusy(true);setError('');const data=Object.fromEntries(new FormData(e.currentTarget));try{onAuthenticated(await api(`/auth/${mode}`,{method:'POST',body:JSON.stringify(data)}));}catch(err){setError(err.message);}finally{setBusy(false);}}
  return <div className="auth-page"><section className="auth-story"><Logo/><div><span className="eyebrow">Your next chapter starts here</span><h1>Find your space.<br/><em>Meet your people.</em></h1><p>RoomLink brings accommodation, compatible roommates and a supportive South African community into one safer place.</p><div className="trust-row"><span><MapPin/>Local listings</span><span><Users/>Better matches</span><span><ShieldCheck/>Safer community</span></div></div><small>Built for students, young professionals and everyone finding their feet.</small></section><section className="auth-panel"><div className="auth-card"><div className="tabs"><button type="button" className={mode==='login'?'active':''} onClick={()=>setMode('login')}>Log in</button><button type="button" className={mode==='register'?'active':''} onClick={()=>setMode('register')}>Create account</button></div><h2>{mode==='login'?'Welcome back':'Join RoomLink ZA'}</h2><p>{mode==='login'?'Good to see you again.':'A better home search is a minute away.'}</p><ErrorBox message={error}/><form onSubmit={submit}>{mode==='register'&&<><div className="field-row"><label>First name<input name="firstName" required/></label><label>Last name<input name="lastName" required/></label></div><div className="field-row"><label>Phone number<input name="phone" type="tel" required/></label><label>Date of birth<input name="dateOfBirth" type="date"/></label></div><div className="field-row"><label>City<input name="city" required/></label><label>Province<select name="province" defaultValue="Gauteng">{provinces.map(x=><option key={x}>{x}</option>)}</select></label></div></>}<label>Email address<input name="email" type="email" placeholder="you@example.com" required/></label><label>Password<input name="password" type="password" minLength="8" placeholder="At least 8 characters" required/></label><button className="primary wide" disabled={busy}>{busy?'Please wait…':mode==='login'?'Log in':'Create my account'}</button></form>{mode==='register'&&<p className="fine"><CheckCircle2 size={15}/> By joining, you agree to help keep RoomLink respectful and safe.</p>}<div className="demo-note"><b>User demo:</b> ayanda@example.com / Password123!<br/><b>Admin demo:</b> admin@roomlink.co.za / Password123!</div></div></section></div>;
}
