import{useEffect,useState}from'react';import{api,date}from'../api.js';import{Avatar,Empty,ErrorBox,Modal}from'../components.jsx';import{CalendarDays,Clock,MapPin,Plus,Star,Users}from'lucide-react';
const normalise=x=>Array.isArray(x)?x:[];
export default function EventsPage(){
 const[items,setItems]=useState([]),[loading,setLoading]=useState(true),[tab,setTab]=useState('upcoming'),[creating,setCreating]=useState(false),[error,setError]=useState('');
 async function load(){setLoading(true);setError('');try{setItems(normalise(await api('/events')))}catch(e){setItems([]);setError(e.message)}finally{setLoading(false)}}useEffect(()=>{load()},[]);
 async function update(path,body){try{await api(path,{method:'PUT',body:JSON.stringify(body)});await load()}catch(e){setError(e.message)}}
 const today=new Date().toISOString().slice(0,10),shown=items.filter(x=>tab==='upcoming'?String(x.event_date||'')>=today:String(x.event_date||'')<today);
 return <div className="page"><section className="page-title"><div><span className="eyebrow">Community calendar</span><h1>Events & activities</h1><p>Meet people, learn together and make your local community feel smaller.</p></div><button className="primary" onClick={()=>setCreating(true)}><Plus/>Create event</button></section><ErrorBox message={error}/>{error&&<button className="secondary retry" onClick={load}>Try again</button>}<div className="admin-tabs"><button className={tab==='upcoming'?'active':''} onClick={()=>setTab('upcoming')}>Upcoming events</button><button className={tab==='past'?'active':''} onClick={()=>setTab('past')}>Past events</button></div>{loading?<div className="page-loading">Loading events…</div>:shown.length?<div className="event-grid">{shown.map(e=><article className="event-card" key={e.id}>{e.image_url&&<div className="event-image" style={{backgroundImage:`url(${e.image_url})`}}/>}<div className="event-content"><span className="eyebrow">{e.category||'Community'}</span><h2>{e.title||'Community event'}</h2><p>{e.description||'No description provided.'}</p><div className="event-meta"><span><CalendarDays/>{date(e.event_date)}</span><span><Clock/>{String(e.event_time||'').slice(0,5)}</span><span><MapPin/>{e.location||'Location to be confirmed'}</span><span><Users/>{Number(e.going_count)||0} going · {Number(e.maybe_count)||0} maybe</span></div><div className="owner"><Avatar size="sm" user={{first_name:e.creator_name?.split(' ')[0],last_name:e.creator_name?.split(' ').slice(1).join(' '),avatar_url:e.creator_avatar}}/><small>Created by <b>{e.creator_name||'RoomLink member'}</b></small></div>{tab==='upcoming'?<div className="event-actions">{[['going','Going'],['maybe','Maybe'],['cant_go',"Can't go"]].map(([v,l])=><button key={v} className={e.my_rsvp===v?'primary':'secondary'} onClick={()=>update(`/events/${e.id}/rsvp`,{response:v})}>{l}</button>)}</div>:<div className="rating"><span>Rate this event</span>{[1,2,3,4,5].map(n=><button key={n} onClick={()=>update(`/events/${e.id}/rating`,{rating:n})}><Star/></button>)}{e.average_rating&&<small>{e.average_rating} average</small>}</div>}</div></article>)}</div>:<Empty title={`No ${tab} events`} body={error?'The events API could not be loaded. Use Try again after restarting the server.':tab==='upcoming'?'Create an activity and invite the community.':'Events you attended will remain here.'}/>} {creating&&<CreateEvent onClose={()=>setCreating(false)} onDone={()=>{setCreating(false);load()}}/>}</div>}
function CreateEvent({onClose,onDone}){const[error,setError]=useState('');async function submit(e){e.preventDefault();try{const body=Object.fromEntries(new FormData(e.currentTarget));if(!body.max_attendees)delete body.max_attendees;if(!body.image_url)delete body.image_url;await api('/events',{method:'POST',body:JSON.stringify(body)});onDone()}catch(x){setError(x.message)}}return <Modal title="Create an event" onClose={onClose}><ErrorBox message={error}/><form onSubmit={submit}><label>Event title<input name="title" required/></label><label>Category<select name="category">{['Social','Game Night','Study Session','Sports','Community','Other'].map(x=><option key={x}>{x}</option>)}</select></label><label>Description<textarea name="description" rows="3"/></label><div className="field-row"><label>Date<input name="event_date" type="date" required/></label><label>Time<input name="event_time" type="time" required/></label></div><label>Location<input name="location" required/></label><div className="field-row"><label>Maximum attendees<input name="max_attendees" type="number" min="1"/></label><label>Event image URL<input name="image_url" type="url"/></label></div><button className="primary wide">Save event</button></form></Modal>}
