import {useEffect,useRef,useState} from 'react';
import {useNavigate,useParams} from 'react-router-dom';
import {api} from '../api.js';
import {Avatar,Empty,ErrorBox,Loader} from '../components.jsx';
import {ArrowLeft,Check,CheckCheck,MessageCircle,RefreshCw,Send} from 'lucide-react';

const chatTime=value=>value?new Intl.DateTimeFormat('en-ZA',{hour:'2-digit',minute:'2-digit'}).format(new Date(value)):'';
const previewTime=value=>{if(!value)return '';const d=new Date(value),today=new Date();return d.toDateString()===today.toDateString()?chatTime(value):new Intl.DateTimeFormat('en-ZA',{day:'2-digit',month:'short'}).format(d);};
const dayLabel=value=>{const d=new Date(value),today=new Date(),yesterday=new Date(Date.now()-86400000);if(d.toDateString()===today.toDateString())return 'Today';if(d.toDateString()===yesterday.toDateString())return 'Yesterday';return new Intl.DateTimeFormat('en-ZA',{dateStyle:'medium'}).format(d);};

export default function MessagesPage({user}){
 const {id}=useParams(),navigate=useNavigate(),[conversations,setConversations]=useState(null),[messages,setMessages]=useState([]),[loadingMessages,setLoadingMessages]=useState(false),[error,setError]=useState(''),[sending,setSending]=useState(false),bottom=useRef(),input=useRef();
 const loadConversations=async()=>{try{setConversations(await api('/messages/conversations'));}catch(e){setError(e.message);setConversations([]);}};
 const loadMessages=async(showLoader=false)=>{if(!id)return;try{if(showLoader)setLoadingMessages(true);const items=await api(`/messages/conversations/${id}/messages`);setMessages(old=>items.length>=old.filter(x=>!x.pending).length?items:old);setError('');await loadConversations();window.dispatchEvent(new Event('roomlink:messages-read'));}catch(e){setError(e.message);}finally{setLoadingMessages(false);}};
 useEffect(()=>{loadConversations();},[]);
 useEffect(()=>{setMessages([]);if(id)loadMessages(true);},[id]);
 useEffect(()=>{const timer=setInterval(()=>{if(document.visibilityState==='visible'){loadConversations();if(id)loadMessages();}},3000);return()=>clearInterval(timer);},[id]);
 useEffect(()=>{const refresh=()=>loadMessages();window.addEventListener('roomlink:message-reacted',refresh);return()=>window.removeEventListener('roomlink:message-reacted',refresh)},[id]);
 async function send(e){e.preventDefault();const form=e.currentTarget,body=new FormData(form).get('body')?.trim();if(!body||sending)return;const tempId='temp-'+Date.now(),optimistic={id:tempId,conversation_id:id,sender_id:user.id,sender_name:`${user.first_name} ${user.last_name}`,body,created_at:new Date().toISOString(),pending:true};setMessages(x=>[...x,optimistic]);form.reset();setSending(true);setError('');try{const saved=await api(`/messages/conversations/${id}/messages`,{method:'POST',body:JSON.stringify({body})});setMessages(x=>x.map(m=>m.id===tempId?saved:m));await loadConversations();}catch(x){setMessages(items=>items.map(m=>m.id===tempId?{...m,pending:false,failed:true}:m));setError(x.message);}finally{setSending(false);input.current?.focus();}}
 const active=conversations?.find(c=>c.id===id),other=active?.members?.[0];
 return <div className="page messages-page"><ErrorBox message={error}/><section className={`messages-layout ${id?'chat-open':''}`}><aside><div className="inbox-title"><div><span className="eyebrow">Your inbox</span><h1>Messages</h1></div><button onClick={loadConversations} aria-label="Refresh conversations"><RefreshCw/></button></div>{conversations===null?<Loader/>:conversations.length?conversations.map(c=>{const member=c.members?.[0];return <button className={c.id===id?'active':''} key={c.id} onClick={()=>navigate('/messages/'+c.id)}><Avatar user={{first_name:member?.name?.split(' ')[0],last_name:member?.name?.split(' ').slice(1).join(' '),avatar_url:member?.avatar_url}}/><div className="conversation-copy"><div><b>{member?.name||'Conversation'}</b><time>{previewTime(c.last_message_at)}</time></div><span className={c.unread_count?'unread-preview':''}>{c.last_sender_id===user.id?'You: ':''}{c.last_message||'Start the conversation'}</span></div>{c.unread_count>0&&<i className="unread-count">{c.unread_count>99?'99+':c.unread_count}</i>}</button>}):<Empty title="No chats yet" body="Open a roommate or listing and choose “Message” to start a private conversation."/>}</aside><article>{id?<><div className="chat-head"><button className="chat-back" onClick={()=>navigate('/messages')}><ArrowLeft/></button><Avatar user={{first_name:other?.name?.split(' ')[0],last_name:other?.name?.split(' ').slice(1).join(' '),avatar_url:other?.avatar_url}}/><div><b>{other?.name||'Conversation'}</b><span>You and {other?.name?.split(' ')[0]||'this member'} · Private chat</span></div></div><div className="chat-body">{loadingMessages?<Loader/>:messages.length?<MessageList messages={messages} user={user}/>:<div className="chat-empty"><MessageCircle/><h2>Start the conversation</h2><p>Send a friendly message to {other?.name?.split(' ')[0]||'this member'}.</p></div>}<div ref={bottom}/></div><form className="message-form" onSubmit={send}><input ref={input} name="body" placeholder={`Message ${other?.name?.split(' ')[0]||''}…`} required maxLength="4000" autoComplete="off"/><button className="primary" disabled={sending} aria-label="Send message"><Send/></button></form></>:<div className="chat-empty"><MessageCircle/><h2>Your conversations live here</h2><p>Choose a chat, or message someone from a listing or roommate profile.</p></div>}</article></section></div>;
}

function MessageList({messages,user}){async function react(messageId,reaction){await api(`/messages/messages/${messageId}/reactions`,{method:'PUT',body:JSON.stringify({reaction})});window.dispatchEvent(new Event('roomlink:message-reacted'))}let previousDay='';return messages.map(m=>{const label=dayLabel(m.created_at),showDay=label!==previousDay;previousDay=label;const mine=m.sender_id===user.id,grouped=Object.entries((m.reactions||[]).reduce((a,x)=>({...a,[x.reaction]:(a[x.reaction]||0)+1}),{}));return <div key={m.id}>{showDay&&<div className="day-divider"><span>{label}</span></div>}<div className={`bubble ${mine?'mine':'theirs'} ${m.failed?'failed':''}`}><span className="bubble-sender">{mine?'You':m.sender_name}</span><p>{m.body}</p>{grouped.length>0&&<div className="message-reaction-counts">{grouped.map(([r,n])=><span key={r}>{r} {n}</span>)}</div>}<div className="message-reactions">{['👍','❤️','😂','🎉'].map(r=><button key={r} onClick={()=>react(m.id,r)}>{r}</button>)}</div><small><time dateTime={m.created_at}>{chatTime(m.created_at)}</time>{mine&&<span className="delivery">{m.failed?'Not sent':m.pending?'Sending…':m.read_at?<><CheckCheck/>Read</>:<><Check/>Sent</>}</span>}</small></div></div>})}
