import {Router} from 'express';import {z} from 'zod';import {query,pool} from '../db/pool.js';import {requireAuth} from '../middleware.js';
const router=Router();router.use(requireAuth);
const member=async(householdId,userId)=>Boolean((await query('SELECT 1 FROM household_members WHERE household_id=$1 AND user_id=$2',[householdId,userId])).rowCount);
async function defaultHousehold(userId){let x=(await query('SELECT h.* FROM households h JOIN household_members m ON m.household_id=h.id WHERE m.user_id=$1 ORDER BY h.created_at LIMIT 1',[userId])).rows[0];if(!x){const c=await pool.connect();try{await c.query('BEGIN');x=(await c.query("INSERT INTO households(name,created_by) VALUES('My household',$1) RETURNING *",[userId])).rows[0];await c.query('INSERT INTO household_members(household_id,user_id) VALUES($1,$2)',[x.id,userId]);await c.query('COMMIT')}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}return x}
router.get('/household',async(req,res,next)=>{try{const h=await defaultHousehold(req.user.id);const [members,chores,bills]=await Promise.all([query(`SELECT u.id,u.first_name,u.last_name,u.avatar_url FROM household_members m JOIN users u ON u.id=m.user_id WHERE m.household_id=$1`,[h.id]),query(`SELECT c.*,u.first_name||' '||u.last_name assignee_name FROM chores c LEFT JOIN users u ON u.id=c.assignee_id WHERE c.household_id=$1 ORDER BY c.status,c.due_date`,[h.id]),query(`SELECT b.*,COALESCE(json_agg(json_build_object('user_id',s.user_id,'amount',s.amount,'paid_at',s.paid_at)) FILTER(WHERE s.user_id IS NOT NULL),'[]') shares FROM bills b LEFT JOIN bill_shares s ON s.bill_id=b.id WHERE b.household_id=$1 GROUP BY b.id ORDER BY b.due_date`,[h.id])]);res.json({household:h,members:members.rows,chores:chores.rows,bills:bills.rows});}catch(e){next(e)}});
router.post('/household/members',async(req,res,next)=>{try{const h=await defaultHousehold(req.user.id),d=z.object({user_id:z.string().uuid()}).parse(req.body);await query('INSERT INTO household_members(household_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[h.id,d.user_id]);res.status(204).end()}catch(e){next(e)}});
router.post('/chores',async(req,res,next)=>{try{const h=await defaultHousehold(req.user.id),d=z.object({title:z.string().min(1).max(160),assignee_id:z.string().uuid().nullable().optional(),due_date:z.string()}).parse(req.body);const {rows}=await query('INSERT INTO chores(household_id,creator_id,title,assignee_id,due_date) VALUES($1,$2,$3,$4,$5) RETURNING *',[h.id,req.user.id,d.title,d.assignee_id||req.user.id,d.due_date]);res.status(201).json(rows[0])}catch(e){next(e)}});
router.patch('/chores/:id',async(req,res,next)=>{try{const status=z.enum(['open','complete']).parse(req.body.status);const {rows}=await query(`UPDATE chores SET status=$1 WHERE id=$2 AND household_id IN(SELECT household_id FROM household_members WHERE user_id=$3) RETURNING *`,[status,req.params.id,req.user.id]);if(!rows[0])return res.status(404).json({error:'Chore not found'});res.json(rows[0])}catch(e){next(e)}});
router.delete('/chores/:id',async(req,res,next)=>{try{await query(`DELETE FROM chores WHERE id=$1 AND household_id IN(SELECT household_id FROM household_members WHERE user_id=$2)`,[req.params.id,req.user.id]);res.status(204).end()}catch(e){next(e)}});
router.post('/bills',async(req,res,next)=>{const c=await pool.connect();try{const h=await defaultHousehold(req.user.id),d=z.object({title:z.string().min(1).max(160),amount:z.coerce.number().positive(),due_date:z.string(),member_ids:z.array(z.string().uuid()).min(1)}).parse(req.body);if(!(await member(h.id,req.user.id)))return res.status(403).json({error:'Household access required'});await c.query('BEGIN');const b=(await c.query('INSERT INTO bills(household_id,creator_id,title,amount,due_date) VALUES($1,$2,$3,$4,$5) RETURNING *',[h.id,req.user.id,d.title,d.amount,d.due_date])).rows[0],share=(d.amount/d.member_ids.length).toFixed(2);for(const uid of d.member_ids)await c.query('INSERT INTO bill_shares(bill_id,user_id,amount) SELECT $1,$2,$3 WHERE EXISTS(SELECT 1 FROM household_members WHERE household_id=$4 AND user_id=$2)',[b.id,uid,share,h.id]);await c.query('COMMIT');res.status(201).json(b)}catch(e){await c.query('ROLLBACK');next(e)}finally{c.release()}});
router.patch('/bills/:id/pay',async(req,res,next)=>{try{const {rows}=await query(`UPDATE bill_shares SET paid_at=CASE WHEN paid_at IS NULL THEN now() ELSE NULL END WHERE bill_id=$1 AND user_id=$2 RETURNING *`,[req.params.id,req.user.id]);if(!rows[0])return res.status(404).json({error:'Bill share not found'});res.json(rows[0])}catch(e){next(e)}});
export default router;
